### ISSUE TITLE
.save() is not inserting a new document

### ISSUE THREAD

**Issue by PeterPilley** [jefersondaniel/pydantic-mongo#11]
Hi,

Just trying out this awesome library and have gotten stuck on commit to the colleciton. if I use .save() then it is not inserting the new document. if i use insert_* then it is working fine.

There is no error being returned so it doesnt look like it is failing

**Comment by Norbiox** [comment]
Hi,
Could you provide the piece of code that does not work the way it's expected?

**Comment by jefersondaniel** [comment]
There was a scenario where the id can be assigned and the save many would try to update a document that does not exists. The default behavior will be to upsert in the version 2 that is being released now.
