### ISSUE TITLE
find_one_by_id logic is different

### ISSUE THREAD

**Issue by anuradhawick** [jefersondaniel/pydantic-mongo#4]
When saving the following object, the correct behaviour happens and adds `_id` in the database field.

```python
class Spam(BaseModel):
    id: ObjectIdField = None
    foo: Foo
    bars: List[Bar]
```

However when I do `result = spam_repository.find_one_by_id(spam.id)` id returns `None`.

The reason is the following.
```python
def find_one_by_id(self, id: str) -> Optional[T]:
        return self.find_one_by({'id': id})
```

I think it should change as;
```python
def find_one_by_id(self, id: str) -> Optional[T]:
        return self.find_one_by({'_id': ObjectId(id)})
```

Can you please publish a new release fixing this? Thanks

**Comment by anuradhawick** [comment]
ObjectId wrapper was also missing, need to;

```python
from bson import ObjectId

# then the query must be
query = {'_id': ObjectId(id)}
```

**Comment by jefersondaniel** [comment]
Hi,

The find_one_by_id had a incorrect typing because it should accept any type since in MongoDB the _id field can store other values than ObjectId.

I updated the documentation
