### ISSUE TITLE
How to annotate a field to keep `mypy` happy

### ISSUE THREAD

**Issue by Jylpah** [jefersondaniel/pydantic-mongo#60]
Hi, 

This is the way to annotate an `ObjectIdField` to keep `mypy==1.8.0` happy. I hope this helps someone. 

```
id: Annotated[ObjectIdField, Field(default_factory=ObjectId)] = ObjectIdField()
```

**Comment by jefersondaniel** [comment]
I changed the README to use a better annotation. Now the `PydanticObjectId` field is exported and the recommended way of creating the id field since its compatible with mypy checks.
