### ISSUE TITLE
Would be nice to have a conda distribution of this on conda-forge

### ISSUE THREAD

**Issue by analog-cbarber** [jefersondaniel/pydantic-mongo#69]
I would like to use this as a dependency of a conda package, so it would be really nice if this was available as a conda package on conda-forge.

**Comment by analog-cbarber** [comment]
Note, this is not too hard to set up for a simple python project like this. 

See https://github.com/conda-forge/staged-recipes

Once it is set up, maintenance is pretty minimal. An automated job will create a PR when it detects a new version of the package on pypi and will ask the maintainers to accept it. If you add or incompatibly change dependencies to the original project, you will need to update them in the conda-forge recipe. That's about it.

**Comment by jefersondaniel** [comment]
Thanks, I'm adding it to conda-forge:

https://github.com/conda-forge/staged-recipes/pull/25526
