### ISSUE TITLE
A question : Can this repository replace Beanie ?

### ISSUE THREAD

**Issue by clabnet** [jefersondaniel/pydantic-mongo#84]
Can this repo replace [Beanie ODM](https://beanie-odm.dev/) ?
Pros ? Cons ?  Sorry for the confusion, I'm a newbie in Python FastAPI & c.

Thank you in advance.

**Comment by jefersondaniel** [comment]
I don't have experience with Beanie but it does seems to be very similar to Django models.

This library is focused on the repository pattern is useful if you already have pydantic models and don't want to mix their logic with database logic.
