### ISSUE TITLE
using both _id and id

### ISSUE THREAD

**Issue by jochman** [jefersondaniel/pydantic-mongo#88]
Hi, in my app I need to use both `id` and `id_`, but by default the package converts all `id` to `id_`.

is there a way to overcome this?

**Comment by robbe-haesendonck** [comment]
Kind of "hacky" but you could use the serialization/deserialization aliases of Pydantic to do this.
For example in your actual pydantic model you define the field "identifier" which you can then serialize to "id".

https://docs.pydantic.dev/latest/concepts/alias/
