### ISSUE TITLE
Problem with update data

### ISSUE THREAD

**Issue by danelsan** [jefersondaniel/pydantic-mongo#91]
I tested on my application, POST, DELETE, GET it's very usefull.
When i have to update an entity, a call 

repo.save(entity);

And the response is:

 UpdateResult({'n': 1, 'upserted': '65f15629c819b74e9d461fe1', 'nModified': 0, 'ok': 1.0, 'updatedExisting': False}, acknowledged=True)

Then i think entity finded but no modified.

Why?

Thans for all

**Comment by jefersondaniel** [comment]
The library code is small so I recommend some debugging for those situations. The code that calls pymongo update is here: https://github.com/jefersondaniel/pydantic-mongo/blob/v2.3.0/pydantic_mongo/abstract_repository.py#L120
